### ISSUE TITLE
About window has black text on dark gray and is hard to read

### ISSUE THREAD

**Issue by gitatmax** [acheronfail/pixel-picker#25] opened 2019-12-20 20:33 UTC
![image](https://user-images.githubusercontent.com/7244793/71290502-00684780-233e-11ea-8607-9a3fdbcee796.png)

**Comment by acheronfail** [comment] 2020-05-22 00:31
Sorry, I never got around to responding to this issue.

I consider this a bug!
But unfortunately, I no longer have a macOS machine.

I'll leave this open in case someone wants to contribute. :)

**Comment by viktorstrate** [comment] 2020-12-17 14:13
I just tried compiling the master branch from source and it seems to work as expected.
It might be the result of a newer version of Xcode.

Built using:
Xcode Version 12.3 (12C33)
MacOS version 11.0.1

Dark mode | Light mode
:-----:|:-----
<img width="396" alt="Screenshot 2020-12-17 at 15 08 55" src="https://user-images.githubusercontent.com/4233458/102498067-c8dbca80-4079-11eb-8dd5-8e649b78cc4f.png"> | <img width="396" alt="Screenshot 2020-12-17 at 15 09 08" src="https://user-images.githubusercontent.com/4233458/102498092-d1340580-4079-11eb-843c-bef86ad47a6c.png">

EDIT:
Just tested the latest homebrew version, and I can confirm that the text is rendered as black on black for that build.

**Comment by acheronfail** [comment] 2020-12-25 00:45
This is fixed with the latest version here: https://github.com/acheronfail/pixel-picker/releases/tag/1.4.1

That said, this version has logging completely disabled due to other issues. :)

**Closed as completed by acheronfail** 2020-12-25 00:45 UTC
Labels: good first issue
